#!/bin/bash

# Use the `ifconfig` command to get active IPv4 IPs
ipv4_addresses=$(ifconfig | grep -oE "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}')

# Display the active IPv4 IPs
for ip_address in $ipv4_addresses; do
    echo $ip_address
done
